_HallOfFameOakText::
	text "OAK: Spectacular"
	line "work, <PLAYER>."
	cont "Truly inspired."
	cont "When you first"
	cont "sat down for my"
	cont "class, years ago,"
	cont "who could have"
	cont "imagined?"

	para "This is the HALL"
	line "of FAME. To be"
	cont "CHAMPION is to"
	cont "become KANTO's"
	cont "guiding light."

	para "Your voice now"
	line "carries great"
	cont "power. Be careful."
	cont "In your journey,"
	cont "have you found"
	cont "the path you would"
	cont "lead us towards?"

	para "100 years ago,"
	line "the first CHAMP"
	cont "stood in this"
	cont "chamber, the"
	cont "SOVEREIGN undone."

	para "They wondered<...>"
	line "what is our"
	cont "responsibility"
	cont "to this world?"
	cont "To Pokémon?"
	cont "To ourselves?"

	para "<PLAYER>! You have"
	line "endeavored hard"
	cont "to reach this"
	cont "hallowed hall."

	para "Decisions can"
	line "begin tomorrow."
	cont "For today,"
	cont "we celebrate!"
	cont "Celebrate you<...>"
	
	para "<...>and your"
	line "dear friends,"
	cont "the Pokémon!"
	done
